# Generated by Django 2.2.3 on 2019-07-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.IntegerField()),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_salary', models.IntegerField()),
                ('employee_city', models.CharField(max_length=50)),
            ],
        ),
    ]
